---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Validating amazon-linux_packer-template.json"
      - ./packer validate scripts/amazon-linux_packer-template.json
      - sleep 600
  build:
    commands:
      - ./packer build scripts/amazon-linux_packer-template.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"
