---
url: "https://34.242.196.111:443/swagger-ui/swagger.yaml"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
